### ISSUE TITLE
Clean UP & Dockerization eos5smc

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5smc#1]

**Comment by pittmanriley** [comment]
I'm having some trouble fetching this model after refactoring. I'm getting the same git lfs issue as I was with other models, but this time there is a 'NoneType object is not iterable' error, which is different than before. I tried doing the `git lfs update --force` command to fix that issue, but it didn't work. Here's the error log: 
[eos5smc.log](https://github.com/ersilia-os/eos5smc/files/12091204/eos5smc.log)

**Comment by GemmaTuron** [comment]
@pittmanriley 
To confirm, you are running simply:
`ersilia -v fetch eos5smc`

This will in principle fetch it from DockerHub so Git LFS should not matter, you could also try specifying --from_docker or from_s3

Let me know if this is doing anything different

**Comment by pittmanriley** [comment]
Hi @GemmaTuron I tried those two, and I couldn't get them to work either. It doesn't seem to be available on Docker, and when I tried fetching from s3 I got this error: 
[eos5smc_from_s3.log](https://github.com/ersilia-os/eos5smc/files/12117190/eos5smc_from_s3.log)

Do you have any ideas where to go from here?

**Comment by GemmaTuron** [comment]
Yes, sorry if you look at the Actions the model did not pass the checks so it did not upload to Docker or S3.

Again, which command are you running? I still not understand if you are getting the git lfs error when clonning the repository or when fetching from the refactored cloned repo.
Anything else than these two options above would not make sense because the model is not updated online, so you can only fetch it from your local, which should not be using Git LFS.

**Comment by pittmanriley** [comment]
@GemmaTuron That Makes sense. I've been unable to fetch by cloning the repository and also when I clone my refactored repo. When I fetch by cloning the repository, I don't think I have a git lfs issue, but I have other errors. Here is that log, which I did from my terminal: 
[eos5smc_repository.log](https://github.com/ersilia-os/eos5smc/files/12131315/eos5smc_repository.log)

When I try fetching from my refactored repo (from my terminal), I also don't seem to be getting the git lfs issue. I think that I was only getting that error when I fetched (both from the repository and refactored repo) if I fetched in codespaces. Here is the error I'm getting when I fetch from my refactored repo: 
[eos5smc_refactored.log](https://github.com/ersilia-os/eos5smc/files/12131336/eos5smc_refactored.log)

**Comment by GemmaTuron** [comment]
Thanks @pittmanriley 

For the first error (fetching without refactoring) it seems clear it is just a dependency issue with python and rdkit, do you agree?

I understand you have solved the rdkit issue in the refactoring, but you are still running into trouble with scipy and torch . This model is  grover-based, so you could check any other grover based model that has already been refactored and check the specifications for dependencies and compare with yours.

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I was able to get the package dependencies working, but I'm running into an error that could either be with scipy or with installing a class from an online GitHub repository called descriptastorus. Here is the error log: 
[eos5smc.log](https://github.com/ersilia-os/eos5smc/files/12165846/eos5smc.log)

 The installation line in the Dockerfile for descriptastorus looks like this: 
`RUN pip install git+https://github.com/bp-kelley/descriptastorus.git@d552f934757378a61dd1799cdb589a864032cd1b`

In the error log, it says that the model `did not produce an outputUnable to make new descriptors, descriptor generator requirements not properly installed`, so I think it might have to do with downloading descriptastorus, but in the error log there is also a line at the end that says `AttributeError: module 'scipy.stats' has no attribute 'gilbrat'`, making me wonder if the issue is with scipy. Do you know if there's something I can do to fix this?

**Comment by GemmaTuron** [comment]
I see! There are two lines in the error log that look problematic:
Yanked version of scipy (potentially not prohibitive to run the model, but would be good to solve)
```
WARNING: The candidate selected for download or install is a yanked version: 'scipy' candidate (version 1.11.0 at https://files.pythonhosted.org/packages/72/08/f9920eeedf4953a631d0087a6e80bb2e091cf51e6efb55ec638d838b4e92/scipy-1.11.0-cp310-cp310-macosx_12_0_arm64.whl (from https://pypi.org/simple/scipy/) (requires-python:<3.13,>=3.9))
Reason for being yanked: License Violation
```
Your system forcing py3.10, as it is a Mac:
```
14:09:03 | WARNING  | This model is trying to install to a python version in ARM64 that is below 3.10. Changing to 3.10.
14:09:03 | DEBUG    | {'version': '0.11.0', 'slim': False, 'python': 'py310'}
```

Like we have done before, I'll bring @simrantan to this issue since she does not have a Mac but a Windows
@simrantan could you help out Riley here? Try to run the model just changing the RDKIT version, nothing else, see if it runs on windows

**Comment by simrantan** [comment]
Hi @GemmaTuron @pittmanriley 

I have tested the model by cloning fetching Riley's fork. I am not receiving the error that Riley is, but I am getting a different one: 
```
10:30:53 | ERROR    | Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos5smc:run did not produce an outputTraceback (most recent call last):
  File "/home/simran/eos/repository/eos5smc/20230726103003_58F757/eos5smc/artifacts/framework/code/main.py", line 11, in <module>
    from model.framework.grover.grover.util.parsing import parse_args, get_newest_train_args
ModuleNotFoundError: No module named 'model'


Hints:
- Visit the fetch troubleshooting site

🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos5smc:run did not produce an outputTraceback (most recent call last):
  File "/home/simran/eos/repository/eos5smc/20230726103003_58F757/eos5smc/artifacts/framework/code/main.py", line 11, in <module>
    from model.framework.grover.grover.util.parsing import parse_args, get_newest_train_args
ModuleNotFoundError: No module named 'model'

```
It appears to be the path is not recognizable for python, so maybe trying a new path for calling util.parsing could help? I am also working on path issues for a grover model, so I can provide insight as I find solutions for my issue. Let me know if the fork is updated so I can test again whenever needed!

**Comment by pittmanriley** [comment]
Hey @simrantan, I adjusted this yesterday but forgot to push it to my repository. Let's hop on a call and try to tackle this together sometime today. 

Thanks for working on it!

**Comment by GemmaTuron** [comment]
Hi,

Thanks for the work, @simrantan please remember to attach the error log, we cannot debug with only this piece of code, we need to see all the installs etc. Let me know when you can test with @pittmanriley updated code

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, @simrantan was able to successfully fetch this model using --from_repo on my cloned repository. It looks like the error I was getting may be a Mac issue. I went ahead and submitted the PR. 

I also didn't realize there were more issues with the workflows, so I see that it failed. I'll wait until that's resolved to submit it again.

**Comment by pittmanriley** [comment]
Hi @GemmaTuron, I submitted the PR today and the checks passed.
